### ISSUE TITLE
Support all TPM fields

### ISSUE THREAD

**Issue by LvffY** [ernestre/terraform-provider-teampasswordmanager#26]
Hi

First of all : thanks for this provider, very useful for me ! :)

I just submit here a feature request : it would be great that this provider would support to manage all fields in a TPM passwords. 

For now, this providers supports the following fields : 

- custom_field_1
- custom_field_10
- custom_field_2
- custom_field_3
- custom_field_4
- custom_field_5
- custom_field_6
- custom_field_7
- custom_field_8
- custom_field_9
- email
- id
- username
- name
- password
- project_id

I think that the other api fields would be great to have : 

 - access_info
 - expiry_date
 - expiry_status
 - external_sharing
 - external_url
 - favorite
 - groups_permissions
 - locked
 - managed_by
 - name
 - notes
 - num_files
 - parents
 - project
 - tags
 - updated_by
 - updated_on
 - user_permission
 - users_permissions

**Comment by ernestre** [comment]
hey, I'm planing to add support for all passwords and projects fields soon 👍

**Comment by LvffY** [comment]
@ernestre Sounds great !

Unrelated question : I just saw that you plan to remove the **api_version** parameters. Do you have any idea when ? 

*TBH my company owns un TPM v4 server and I'm not aware about any upgrade plan ... So it would be great if you support at least v4 and v5 API but I understand that this could be challenging*

**Comment by ernestre** [comment]
For now I don't plan removing it any time soon, so you should be safe.

**Comment by ernestre** [comment]
> access_info
expiry_date
expiry_status
external_sharing
external_url
favorite
groups_permissions
locked
managed_by
name
notes
num_files
parents
project
tags
updated_by
updated_on
user_permission
users_permissions

These fields are now available in [v0.4.0](https://registry.terraform.io/providers/ernestre/teampasswordmanager/latest/docs/resources/password#schema)
